version: '3'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: curriculumDB
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: